Update README.md
TheThingsNetwork/ttn pull request #769
Opened 2019-12-31 10:39 UTC by DurgaPrasadWebDev

2019-12-31 10:40 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TheThingsNetwork/ttn?pullRequest=769) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TheThingsNetwork/ttn?pullRequest=769) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TheThingsNetwork/ttn?pullRequest=769) it.</sub>

2020-01-02 06:41 UTC, htdvisser requested changes
Thanks for the improvement, @DurgaPrasadWebDev!

These docs are generated, so this line would actually need to be updated in

https://github.com/TheThingsNetwork/ttn/blob/develop/ttnctl/cmd/gateways_collaborators_add.go#L13

after which the docs can be regenerated with `make docs`.

2020-05-04 23:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TheThingsNetwork/ttn?pullRequest=769) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TheThingsNetwork/ttn?pullRequest=769) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TheThingsNetwork/ttn?pullRequest=769) it.</sub>

2020-05-06 16:37 UTC, johanstokking commented
@DurgaPrasadWebDev will you update this PR? Thanks in advance!

2021-12-14 09:37 UTC, htdvisser commented
With The Things Network V2 shut down, we're going to archive this repository. This pull request will be locked.

2021-12-14 09:37 UTC, closed without merging